// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TImViecAPI.Data;

#nullable disable

namespace TImViecAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251016050124_Addreset")]
    partial class Addreset
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TImViecAPI.Model.BangCap", b =>
                {
                    b.Property<int>("bcid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("bcid"));

                    b.Property<string>("bcName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("bcid");

                    b.ToTable("BangCap");
                });

            modelBuilder.Entity("TImViecAPI.Model.BaoCao", b =>
                {
                    b.Property<int>("bcid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("bcid"));

                    b.Property<DateTime?>("NgayBao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NoiDungBao")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("bcid");

                    b.ToTable("BaoCao");
                });

            modelBuilder.Entity("TImViecAPI.Model.ChucDanh", b =>
                {
                    b.Property<int>("cdid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("cdid"));

                    b.Property<string>("cdName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("cdid");

                    b.ToTable("ChucDanh");
                });

            modelBuilder.Entity("TImViecAPI.Model.CongTy", b =>
                {
                    b.Property<int>("ctid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ctid"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Logo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaThue")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MieuTa")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MoHinh")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NguoiLienHe")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("QuocGia")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("SoNhanVien")
                        .HasColumnType("int");

                    b.Property<string>("ctName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("sdtCongTy")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("sdtLienHe")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("ctid");

                    b.ToTable("CongTy");
                });

            modelBuilder.Entity("TImViecAPI.Model.HoSo", b =>
                {
                    b.Property<int>("hsid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("hsid"));

                    b.Property<string>("ViTriFile")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("hsName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("ungvienID")
                        .HasColumnType("int");

                    b.HasKey("hsid");

                    b.HasIndex("ungvienID");

                    b.ToTable("HoSo");
                });

            modelBuilder.Entity("TImViecAPI.Model.HoSo_UngTuyen", b =>
                {
                    b.Property<int>("hosoID")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("ungtuyenID")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.HasKey("hosoID", "ungtuyenID");

                    b.HasIndex("ungtuyenID");

                    b.ToTable("HoSo_UngTuyen");
                });

            modelBuilder.Entity("TImViecAPI.Model.KinhNghiem", b =>
                {
                    b.Property<int>("knid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("knid"));

                    b.Property<string>("knName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("knid");

                    b.ToTable("KinhNghiem");
                });

            modelBuilder.Entity("TImViecAPI.Model.KinhNgiem", b =>
                {
                    b.Property<int>("knid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("knid"));

                    b.Property<string>("ChucVu")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("TGBatDau")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("TGKetThuc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TenCongTy")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("knid");

                    b.ToTable("KinhNgiem");
                });

            modelBuilder.Entity("TImViecAPI.Model.LinhVuc", b =>
                {
                    b.Property<int>("lvid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("lvid"));

                    b.Property<string>("lvName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("lvid");

                    b.ToTable("LinhVuc");
                });

            modelBuilder.Entity("TImViecAPI.Model.LoaiHinhLamViec", b =>
                {
                    b.Property<int>("lhid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("lhid"));

                    b.Property<string>("lhName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("lhid");

                    b.ToTable("LoaiHinhLamViec");
                });

            modelBuilder.Entity("TImViecAPI.Model.NguoiDung", b =>
                {
                    b.Property<int>("tkid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("tkid"));

                    b.Property<string>("mail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("sdt")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("tkName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("tkid");

                    b.ToTable("NguoiDung");
                });

            modelBuilder.Entity("TImViecAPI.Model.NguoiDung_ThongBao", b =>
                {
                    b.Property<int>("nguoidungID")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("thongbaoID")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.Property<bool>("DaXem")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("nguoidungID", "thongbaoID");

                    b.HasIndex("thongbaoID");

                    b.ToTable("NguoiDung_ThongBao");
                });

            modelBuilder.Entity("TImViecAPI.Model.NhaTuyenDung", b =>
                {
                    b.Property<int>("ntdid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ctID")
                        .HasColumnType("int");

                    b.Property<string>("ntdName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("ntdid");

                    b.HasIndex("ctID");

                    b.ToTable("NhaTuyenDung");
                });

            modelBuilder.Entity("TImViecAPI.Model.NoiDungHoSo", b =>
                {
                    b.Property<int>("ndid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ndid"));

                    b.Property<string>("HocVan")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MailHoSo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("NamKinhNghiem")
                        .HasColumnType("int");

                    b.Property<string>("PhoneHoSo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TenUngVien")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("hosoID")
                        .HasColumnType("int");

                    b.HasKey("ndid");

                    b.HasIndex("hosoID");

                    b.ToTable("NoiDungHoSo");
                });

            modelBuilder.Entity("TImViecAPI.Model.NoiDung_KinhNghiem", b =>
                {
                    b.Property<int>("noidungID")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("kinhnghiemID")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.HasKey("noidungID", "kinhnghiemID");

                    b.HasIndex("kinhnghiemID");

                    b.ToTable("NoiDung_KinhNghiem");
                });

            modelBuilder.Entity("TImViecAPI.Model.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("TkId")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("TkId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("TImViecAPI.Model.PhucLoi", b =>
                {
                    b.Property<int>("plid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("plid"));

                    b.Property<string>("plName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("plid");

                    b.ToTable("PhucLoi");
                });

            modelBuilder.Entity("TImViecAPI.Model.TInTuyenDung", b =>
                {
                    b.Property<int>("ttdid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ttdid"));

                    b.Property<bool?>("DaDuyet")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("HanNop")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MieuTa")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("NgayDang")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TieuDe")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("Tuoi")
                        .HasColumnType("int");

                    b.Property<int?>("YeuCau")
                        .HasColumnType("int");

                    b.Property<int?>("bangcapID")
                        .HasColumnType("int");

                    b.Property<int?>("chucdanhID")
                        .HasColumnType("int");

                    b.Property<int?>("kinhnghiemID")
                        .HasColumnType("int");

                    b.Property<int?>("linhvucIID")
                        .HasColumnType("int");

                    b.Property<int?>("loaihinhID")
                        .HasColumnType("int");

                    b.Property<int?>("nhaTuyenDungID")
                        .HasColumnType("int");

                    b.Property<int?>("vitriID")
                        .HasColumnType("int");

                    b.HasKey("ttdid");

                    b.HasIndex("bangcapID");

                    b.HasIndex("chucdanhID");

                    b.HasIndex("kinhnghiemID");

                    b.HasIndex("linhvucIID");

                    b.HasIndex("loaihinhID");

                    b.HasIndex("nhaTuyenDungID");

                    b.HasIndex("vitriID");

                    b.ToTable("TInTuyenDung");
                });

            modelBuilder.Entity("TImViecAPI.Model.TInTuyenDung_PhucLoi", b =>
                {
                    b.Property<int>("tintuyendungID")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("phucloiID")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.HasKey("tintuyendungID", "phucloiID");

                    b.HasIndex("phucloiID");

                    b.ToTable("TInTuyenDung_PhucLoi");
                });

            modelBuilder.Entity("TImViecAPI.Model.ThongBao", b =>
                {
                    b.Property<int>("tbid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("tbid"));

                    b.Property<DateTime?>("NgayBao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("tbid");

                    b.ToTable("ThongBao");
                });

            modelBuilder.Entity("TImViecAPI.Model.UngTuyen", b =>
                {
                    b.Property<int>("utid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("utid"));

                    b.Property<DateTime?>("NgayNop")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("tintuyendungid")
                        .HasColumnType("int");

                    b.HasKey("utid");

                    b.HasIndex("tintuyendungid");

                    b.ToTable("UngTuyen");
                });

            modelBuilder.Entity("TImViecAPI.Model.UngVien", b =>
                {
                    b.Property<int>("uvid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("QuocGia")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("linhvucID")
                        .HasColumnType("int");

                    b.Property<string>("uvName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("uvid");

                    b.HasIndex("linhvucID");

                    b.ToTable("UngVien");
                });

            modelBuilder.Entity("TImViecAPI.Model.UngVien_BaoCao", b =>
                {
                    b.Property<int>("ungvienID")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("baocaoID")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.HasKey("ungvienID", "baocaoID");

                    b.HasIndex("baocaoID");

                    b.ToTable("UngVien_BaoCao");
                });

            modelBuilder.Entity("TImViecAPI.Model.UngVien_UngTuyen", b =>
                {
                    b.Property<int>("ungvienID")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("ungtuyenID")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.HasKey("ungvienID", "ungtuyenID");

                    b.HasIndex("ungtuyenID");

                    b.ToTable("UngVien_UngTuyen");
                });

            modelBuilder.Entity("TImViecAPI.Model.ViTri", b =>
                {
                    b.Property<int>("vtid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("vtid"));

                    b.Property<string>("vtName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("vtid");

                    b.ToTable("ViTri");
                });

            modelBuilder.Entity("TImViecAPI.Model.HoSo", b =>
                {
                    b.HasOne("TImViecAPI.Model.UngVien", "UngVien")
                        .WithMany()
                        .HasForeignKey("ungvienID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("UngVien");
                });

            modelBuilder.Entity("TImViecAPI.Model.HoSo_UngTuyen", b =>
                {
                    b.HasOne("TImViecAPI.Model.HoSo", "HoSo")
                        .WithMany()
                        .HasForeignKey("hosoID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TImViecAPI.Model.UngTuyen", "UngTuyen")
                        .WithMany()
                        .HasForeignKey("ungtuyenID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("HoSo");

                    b.Navigation("UngTuyen");
                });

            modelBuilder.Entity("TImViecAPI.Model.NguoiDung_ThongBao", b =>
                {
                    b.HasOne("TImViecAPI.Model.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("nguoidungID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TImViecAPI.Model.ThongBao", "ThongBao")
                        .WithMany()
                        .HasForeignKey("thongbaoID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("NguoiDung");

                    b.Navigation("ThongBao");
                });

            modelBuilder.Entity("TImViecAPI.Model.NhaTuyenDung", b =>
                {
                    b.HasOne("TImViecAPI.Model.CongTy", "CongTy")
                        .WithMany()
                        .HasForeignKey("ctID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("TImViecAPI.Model.NguoiDung", "NguoiDung")
                        .WithOne()
                        .HasForeignKey("TImViecAPI.Model.NhaTuyenDung", "ntdid")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CongTy");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("TImViecAPI.Model.NoiDungHoSo", b =>
                {
                    b.HasOne("TImViecAPI.Model.HoSo", "HoSo")
                        .WithMany()
                        .HasForeignKey("hosoID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("HoSo");
                });

            modelBuilder.Entity("TImViecAPI.Model.NoiDung_KinhNghiem", b =>
                {
                    b.HasOne("TImViecAPI.Model.KinhNgiem", "KinhNgiem")
                        .WithMany()
                        .HasForeignKey("kinhnghiemID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TImViecAPI.Model.NoiDungHoSo", "NoiDungHoSo")
                        .WithMany()
                        .HasForeignKey("noidungID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("KinhNgiem");

                    b.Navigation("NoiDungHoSo");
                });

            modelBuilder.Entity("TImViecAPI.Model.PasswordResetToken", b =>
                {
                    b.HasOne("TImViecAPI.Model.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("TkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("TImViecAPI.Model.TInTuyenDung", b =>
                {
                    b.HasOne("TImViecAPI.Model.BangCap", "BangCap")
                        .WithMany()
                        .HasForeignKey("bangcapID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("TImViecAPI.Model.ChucDanh", "ChucDanh")
                        .WithMany()
                        .HasForeignKey("chucdanhID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("TImViecAPI.Model.KinhNghiem", "KinhNghiem")
                        .WithMany()
                        .HasForeignKey("kinhnghiemID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("TImViecAPI.Model.LinhVuc", "LinhVuc")
                        .WithMany()
                        .HasForeignKey("linhvucIID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("TImViecAPI.Model.LoaiHinhLamViec", "LoaiHinhLamViec")
                        .WithMany()
                        .HasForeignKey("loaihinhID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("TImViecAPI.Model.NhaTuyenDung", "NhaTuyenDung")
                        .WithMany()
                        .HasForeignKey("nhaTuyenDungID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("TImViecAPI.Model.ViTri", "ViTri")
                        .WithMany()
                        .HasForeignKey("vitriID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("BangCap");

                    b.Navigation("ChucDanh");

                    b.Navigation("KinhNghiem");

                    b.Navigation("LinhVuc");

                    b.Navigation("LoaiHinhLamViec");

                    b.Navigation("NhaTuyenDung");

                    b.Navigation("ViTri");
                });

            modelBuilder.Entity("TImViecAPI.Model.TInTuyenDung_PhucLoi", b =>
                {
                    b.HasOne("TImViecAPI.Model.PhucLoi", "PhucLoi")
                        .WithMany()
                        .HasForeignKey("phucloiID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TImViecAPI.Model.TInTuyenDung", "TInTuyenDung")
                        .WithMany()
                        .HasForeignKey("tintuyendungID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("PhucLoi");

                    b.Navigation("TInTuyenDung");
                });

            modelBuilder.Entity("TImViecAPI.Model.UngTuyen", b =>
                {
                    b.HasOne("TImViecAPI.Model.TInTuyenDung", "TInTuyenDung")
                        .WithMany()
                        .HasForeignKey("tintuyendungid")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("TInTuyenDung");
                });

            modelBuilder.Entity("TImViecAPI.Model.UngVien", b =>
                {
                    b.HasOne("TImViecAPI.Model.LinhVuc", "LinhVuc")
                        .WithMany()
                        .HasForeignKey("linhvucID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("TImViecAPI.Model.NguoiDung", "NguoiDung")
                        .WithOne()
                        .HasForeignKey("TImViecAPI.Model.UngVien", "uvid")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("LinhVuc");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("TImViecAPI.Model.UngVien_BaoCao", b =>
                {
                    b.HasOne("TImViecAPI.Model.BaoCao", "BaoCao")
                        .WithMany()
                        .HasForeignKey("baocaoID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TImViecAPI.Model.UngVien", "UngVien")
                        .WithMany()
                        .HasForeignKey("ungvienID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BaoCao");

                    b.Navigation("UngVien");
                });

            modelBuilder.Entity("TImViecAPI.Model.UngVien_UngTuyen", b =>
                {
                    b.HasOne("TImViecAPI.Model.UngTuyen", "UngTuyen")
                        .WithMany()
                        .HasForeignKey("ungtuyenID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TImViecAPI.Model.UngVien", "UngVien")
                        .WithMany()
                        .HasForeignKey("ungvienID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("UngTuyen");

                    b.Navigation("UngVien");
                });
#pragma warning restore 612, 618
        }
    }
}
